import Head from "next/head";
import { Inter } from "@next/font/google";
import Welcome from "../components/Welcome";
import Overview from "../components/Overview";
import Experience from "../components/Experience";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="scroll-smooth max-h-screen overflow-y-scroll overflow-x-hidden scrollbar-none">
        <Welcome />
        <Overview />
        <Experience />
      </div>
    </>
  );
}
